/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

// TapData Documentation docs list
  TapData: [
  'what-is-tapview',
  'introduction/security', 
{
         type: 'category',
         label: 'Connectors',
         link: {type: 'doc', id: 'prerequisites/README'},
         items: [
             'prerequisites/oracle',
             'prerequisites/mysql',
             'prerequisites/mariadb',
             'prerequisites/mongodb',
             'prerequisites/mongodb-atlas',
             'prerequisites/postgresql',
             'prerequisites/sqlserver',
             'prerequisites/sybase',
             'prerequisites/kafka',
             'prerequisites/csv',
             'prerequisites/db2',
         ]
    },
    {
     type: 'category',
     label: 'Quick Start',
     link: {type: 'doc', id: 'quick-start/README'},
     items: [
            'quick-start/install',
            'quick-start/connect-database',
            'quick-start/create-task',
     ]
    },
    {
     type: 'category',
     label: 'Billing',
     link: {type: 'doc', id: 'billing/README'},
     items: [
             'billing/billing-overview',
             'billing/renew-subscribe',
             'billing/expiration',
       ]
    }
 ]
};

module.exports = sidebars;
